export const authCopy = {
  en: {
    eyebrow: 'Welcome back',
    title: <>Login to<br/><span>ATRC Talent.</span></>,
    intro: 'Enter your details to continue. This client preview does not check your credentials — selecting Continue always opens your account area.',
    emailLabel: 'Email or username',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    continue: 'Continue',
    forgotPassword: 'Forgot password?',
    orDivider: 'or continue with',
    uaePass: 'Continue with UAE Pass',
    otp: 'Continue with mobile OTP',
    noAccount: 'New to ATRC Talent?',
    register: 'Create an account',
    accountEyebrow: 'Your account',
    accountTitle: <>You're signed in.<br/><span>Welcome to ATRC Talent.</span></>,
    accountText: 'This is a placeholder account area for the current client-only stage. Full Profile, Saved Items, Career Planner progress and CV Builder land in upcoming increments.',
    signedInVia: (method) => `Signed in via ${method}`,
    logout: 'Logout',
    backHome: 'Back to Home',
  },
  ar: {
    eyebrow: 'مرحباً بعودتك',
    title: <>تسجيل الدخول إلى<br/><span>مواهب ATRC.</span></>,
    intro: 'أدخل بياناتك للمتابعة. لا تتحقق هذه المعاينة التجريبية من صحة بياناتك؛ اختيار "متابعة" يفتح دائماً منطقة حسابك.',
    emailLabel: 'البريد الإلكتروني أو اسم المستخدم',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'كلمة المرور',
    passwordPlaceholder: '••••••••',
    continue: 'متابعة',
    forgotPassword: 'نسيت كلمة المرور؟',
    orDivider: 'أو تابع باستخدام',
    uaePass: 'المتابعة عبر الهوية الرقمية UAE Pass',
    otp: 'المتابعة برمز التحقق عبر الهاتف',
    noAccount: 'جديد على مواهب ATRC؟',
    register: 'إنشاء حساب',
    accountEyebrow: 'حسابك',
    accountTitle: <>تم تسجيل دخولك.<br/><span>مرحباً بك في مواهب ATRC.</span></>,
    accountText: 'هذه منطقة حساب مؤقتة لمرحلة العميل الحالية. سيتم إضافة الملف الشخصي الكامل والعناصر المحفوظة وتقدم مخطط المسار المهني ومنشئ السيرة الذاتية في الزيادات القادمة.',
    signedInVia: (method) => `تم تسجيل الدخول عبر ${method}`,
    logout: 'تسجيل الخروج',
    backHome: 'العودة إلى الرئيسية',
  },
}
