export const careerTestCopy = {
  en: {
    eyebrow: 'Career Test',
    title: <>Which future<br/><span>fits you best?</span></>,
    intro: 'Answer eight short questions about how you think, learn and want to spend your time. There are no right or wrong answers — only the pathway that fits you.',
    instructionsTitle: 'How it works',
    instructions: ['Eight quick questions, no research or preparation needed', 'Pick the option that feels most like you', 'Go back and change an answer at any time before you finish', 'Your progress is saved on this device if you leave and come back'],
    startTest: 'Start Test',
    resumeTest: 'Resume Test',
    startOver: 'Start over',
    viewLastResult: 'View your last result',
    questionProgress: (current, total) => `Question ${current} of ${total}`,
    previous: 'Previous',
    next: 'Next',
    seeResults: 'See Results',
    resultEyebrow: 'Your result',
    resultTitle: 'Your primary pathway match',
    secondaryTitle: 'Other pathways worth exploring',
    viewPathway: 'View this pathway',
    retakeTest: 'Retake the test',
    exploreTechnologies: 'Explore matching technologies',
    noResultTitle: 'No saved result yet',
    noResultText: 'Take the Career Test to get your personalised pathway match.',
    noProgressTitle: 'No test in progress',
    noProgressText: 'Start the Career Test to begin answering questions.',
    backToTest: 'Back to Career Test',
  },
  ar: {
    eyebrow: 'اختبار المسار المهني',
    title: <>أي مستقبل<br/><span>يناسبك أكثر؟</span></>,
    intro: 'أجب عن ثماني أسئلة قصيرة حول طريقة تفكيرك وتعلّمك وكيف تحب أن تقضي وقتك. لا توجد إجابات صحيحة أو خاطئة، فقط المسار الذي يناسبك.',
    instructionsTitle: 'كيف يعمل الاختبار',
    instructions: ['ثمانية أسئلة سريعة دون حاجة إلى بحث أو تحضير', 'اختر الخيار الأقرب إلى طبيعتك', 'يمكنك الرجوع وتغيير إجابتك في أي وقت قبل الإنهاء', 'يُحفظ تقدمك على هذا الجهاز إذا غادرت وعدت لاحقاً'],
    startTest: 'ابدأ الاختبار',
    resumeTest: 'استكمال الاختبار',
    startOver: 'ابدأ من جديد',
    viewLastResult: 'عرض نتيجتك السابقة',
    questionProgress: (current, total) => `السؤال ${current} من ${total}`,
    previous: 'السابق',
    next: 'التالي',
    seeResults: 'عرض النتائج',
    resultEyebrow: 'نتيجتك',
    resultTitle: 'مسارك المهني الأساسي المطابق',
    secondaryTitle: 'مسارات أخرى تستحق الاستكشاف',
    viewPathway: 'عرض هذا المسار',
    retakeTest: 'أعد الاختبار',
    exploreTechnologies: 'استكشف التقنيات المطابقة',
    noResultTitle: 'لا توجد نتيجة محفوظة بعد',
    noResultText: 'أجرِ اختبار المسار المهني للحصول على مسارك المهني الشخصي.',
    noProgressTitle: 'لا يوجد اختبار قيد التنفيذ',
    noProgressText: 'ابدأ اختبار المسار المهني للإجابة عن الأسئلة.',
    backToTest: 'العودة إلى اختبار المسار المهني',
  },
}
