export const iphoneCopy = {
  en: {
    open: 'Open iPhone experience',
    return: 'Return to Web',
    status: 'Experience shell · Build 01',
    eyebrow: 'ATRC Talent on iPhone',
    title: <>Your future.<br/><span>Always within reach.</span></>,
    lead: 'A focused mobile space for discovering paths, building momentum and staying connected to what comes next.',
    signal: 'Mobile foundation in progress',
    dashboard: 'Dashboard',
    recommended: 'Recommended next action',
    startCareerTest: 'Start Career Test',
    openRoute: 'Open',
    viewDetails: 'View details',
    saved: 'Saved',
    reports: 'Reports',
    programs: 'Programs',
    profile: 'Profile',
    planner: 'Planner',
    habits: 'Habits',
    aiChat: 'AI Career Buddy',
    cvBuilder: 'CV Builder',
    settings: 'Settings',
    preview: 'Preview',
    unavailable: 'This mobile surface is staged in-frame for the current client build. It sends no external requests and keeps the route shareable.',
    notFound: 'iPhone route not found',
    notFoundText: 'This direct link is not in the current mobile route map.',
    goDashboard: 'Go to Dashboard',
    technologies: 'Technologies',
    pathways: 'Pathways',
    search: 'Search',
    account: 'Account',
    login: 'Login',
    buildStatus: 'Client-only',
    highlights: [
      ['Discover', 'Technologies, pathways and opportunities shaped for a smaller screen.', '01'],
      ['Build', 'Career decisions, plans and progress gathered into one clear rhythm.', '02'],
      ['Grow', 'Daily habits and next actions designed to keep ambition moving.', '03'],
    ],
    tabs: ['Home', 'Explore', 'Planner', 'Habits', 'Profile'],
  },
  ar: {
    open: 'افتح تجربة آيفون',
    return: 'العودة إلى الويب',
    status: 'واجهة التجربة · الإصدار 01',
    eyebrow: 'مواهب ATRC على آيفون',
    title: <>مستقبلك.<br/><span>دائماً في متناولك.</span></>,
    lead: 'مساحة جوّال مركّزة لاكتشاف المسارات وبناء الزخم والبقاء على اتصال بما هو قادم.',
    signal: 'الأساس المحمول قيد التطوير',
    dashboard: 'لوحة التحكم',
    recommended: 'الإجراء التالي المقترح',
    startCareerTest: 'ابدأ اختبار المسار',
    openRoute: 'افتح',
    viewDetails: 'عرض التفاصيل',
    saved: 'المحفوظات',
    reports: 'التقارير',
    programs: 'البرامج',
    profile: 'الملف',
    planner: 'المخطط',
    habits: 'العادات',
    aiChat: 'مساعد المسار بالذكاء الاصطناعي',
    cvBuilder: 'منشئ السيرة الذاتية',
    settings: 'الإعدادات',
    preview: 'معاينة',
    unavailable: 'هذه الواجهة المحمولة مهيأة داخل الإطار في الإصدار الحالي. لا ترسل أي طلبات خارجية وتبقي الرابط قابلاً للمشاركة.',
    notFound: 'مسار آيفون غير موجود',
    notFoundText: 'هذا الرابط المباشر غير موجود في خريطة المسارات المحمولة الحالية.',
    goDashboard: 'اذهب إلى لوحة التحكم',
    technologies: 'التقنيات',
    pathways: 'المسارات',
    search: 'البحث',
    account: 'الحساب',
    login: 'تسجيل الدخول',
    buildStatus: 'عميل فقط',
    highlights: [
      ['اكتشف', 'تقنيات ومسارات وفرص مصمّمة بوضوح للشاشة الصغيرة.', '01'],
      ['ابنِ', 'قراراتك وخططك وتقدّمك ضمن إيقاع واحد واضح.', '02'],
      ['تطوّر', 'عادات يومية وخطوات تالية تحافظ على حركة طموحك.', '03'],
    ],
    tabs: ['الرئيسية', 'استكشف', 'المخطط', 'العادات', 'الملف'],
  },
}
