export const registerCopy = {
  en: {
    eyebrow: 'Create your account',
    title: <>Join<br/><span>ATRC Talent.</span></>,
    intro: 'Choose the role that best describes you. This client preview does not validate your details — completing the form always opens your account area.',
    roleStudent: 'Student', roleStudentText: 'Explore technologies, take the Career Test and build your profile.',
    roleParent: 'Parent', roleParentText: 'Support your child’s journey and track their progress.',
    roleEducator: 'Educator', roleEducatorText: 'Guide students and connect them with opportunities.',
    roleOther: 'Other', roleOtherText: 'Explore ATRC Talent as a professional or supporter.',
    comingSoon: 'Available in a future update',
    accountInfoTitle: 'Account information',
    firstName: 'First name', lastName: 'Last name', birthYear: 'Birth year', email: 'Email', password: 'Password', mobile: 'Mobile number',
    studentInfoTitle: 'Student information',
    gender: 'Gender', genderMale: 'Male', genderFemale: 'Female',
    nationality: 'Nationality', emirate: 'Emirate', grade: 'Grade / year', curriculum: 'Curriculum', communicationPreference: 'Communication preference',
    consent: 'I agree to the Terms and Privacy Policy',
    createAccount: 'Create Account',
    backToRoles: 'Choose a different role',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Login',
  },
  ar: {
    eyebrow: 'أنشئ حسابك',
    title: <>انضم إلى<br/><span>مواهب ATRC.</span></>,
    intro: 'اختر الدور الذي يصفك بشكل أفضل. لا تتحقق هذه المعاينة التجريبية من بياناتك؛ إكمال النموذج يفتح دائماً منطقة حسابك.',
    roleStudent: 'طالب', roleStudentText: 'استكشف التقنيات، وأجرِ اختبار المسار المهني، وابنِ ملفك الشخصي.',
    roleParent: 'ولي أمر', roleParentText: 'دعم مسار طفلك وتتابع تقدمه.',
    roleEducator: 'معلّم', roleEducatorText: 'وجّه الطلاب وصِلهم بالفرص المناسبة.',
    roleOther: 'أخرى', roleOtherText: 'استكشف مواهب ATRC كمهني أو داعم.',
    comingSoon: 'متوفر في تحديث قادم',
    accountInfoTitle: 'معلومات الحساب',
    firstName: 'الاسم الأول', lastName: 'اسم العائلة', birthYear: 'سنة الميلاد', email: 'البريد الإلكتروني', password: 'كلمة المرور', mobile: 'رقم الهاتف المتحرك',
    studentInfoTitle: 'معلومات الطالب',
    gender: 'الجنس', genderMale: 'ذكر', genderFemale: 'أنثى',
    nationality: 'الجنسية', emirate: 'الإمارة', grade: 'الصف / السنة', curriculum: 'المنهج الدراسي', communicationPreference: 'وسيلة التواصل المفضلة',
    consent: 'أوافق على الشروط وسياسة الخصوصية',
    createAccount: 'إنشاء حساب',
    backToRoles: 'اختر دوراً مختلفاً',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    login: 'تسجيل الدخول',
  },
}
