export const uiCopy = {
  en: {
    mainNavigation: 'Main navigation', switchLanguage: 'Switch language', toggleMenu: 'Toggle menu', orbitAria: 'Explore future technologies',
    filmPlay: 'Play film', filmPause: 'Pause film', filmMute: 'Mute film', filmUnmute: 'Unmute film',
    signalsEyebrow: 'Signals of the future', signalsTitle: <>The future is already<br/><span>in motion.</span></>,
    missionEyebrow: 'Our mission', missionTitle: <>Empowering the next generation of innovators to <span>shape the future world.</span></>,
    missionText: 'Your ideas matter. Your curiosity has power. ATRC Talent connects you with the knowledge and opportunities to turn both into impact.', missionCta: 'About ATRC Talent',
    directionEyebrow: 'Find your direction', directionTitle: <>More than a career.<br/><span>A pathway to impact.</span></>, directionCta: 'View all pathways',
    quizEyebrow: 'Not sure where to start?', quizTitle: <>Your future might be<br/>one question away.</>,
    innerIntro: 'Use this page as a launch point to choose the right domain, understand the next steps and connect curiosity with real opportunities.',
    startExploring: 'Start exploring', whatYouFind: 'What you will find', chooseSignal: <>Choose a signal.<br/><span>Follow the momentum.</span></>, explore: 'Explore',
    howItWorks: 'How it works', clearPath: 'A clear path from interest to action.', findMatch: 'Find your match', pathQuestion: <>Which path fits<br/>the way you think?</>,
    techKicker: 'Explore the building blocks of tomorrow', techTitle: <>Advanced<br/><span>Technologies</span></>, techLead: 'From quantum systems to intelligent machines, explore the fields redefining what’s possible — and the people who will lead them.',
    techSearch: 'Search technologies or careers', results: 'results', filterAria: 'Filter technologies', all: 'All',
    save: 'Save', remove: 'Remove', exploreTechnology: 'Explore technology', noSignal: 'No signal found.', noSignalText: 'Try another technology, career or category.', resetSearch: 'Reset search',
    techSignalEyebrow: 'From idea to domain', techSignalTitle: <>Technology gets clearer<br/><span>when you see where it works.</span></>,
    techSignals: [
      ['Discover', 'Scan the fields that match your curiosity.', '01'],
      ['Compare', 'Understand how careers and capabilities connect.', '02'],
      ['Commit', 'Save the signals that deserve a deeper look.', '03'],
    ],
    techQuestion: <>Which future technology<br/>fits the way you think?</>,
    footerNavigation: 'Footer navigation', ecosystem: 'ATRC ecosystem', location: 'Abu Dhabi, United Arab Emirates', privacy: 'Privacy', terms: 'Terms', accessibility: 'Accessibility',
    footerTagline: <>Talent. Technology.<br/>Transformation.</>, visitAtrc: 'Visit ATRC.gov.ae', exploreGroup: 'Explore', supportGroup: 'Support', legalGroup: 'Legal', about: 'About', contact: 'Contact', faq: 'FAQ', usefulMaterials: 'Useful Materials',
    backToCatalogue: 'Back to Technologies', introduction: 'Introduction', whyItMatters: 'Why it matters', keySubjects: 'Key subjects to study', technologyDomains: 'Technology domains', technologyGoals: 'Technology goals',
    educationRequirements: 'Education requirements', professions: 'Professions', responsibilities: 'Responsibilities', requiredQualifications: 'Required qualifications', qualificationLevels: 'Qualification levels',
    recommendedProgrammes: 'Recommended programmes', studyRoutes: 'Study routes', universitiesUae: 'UAE universities', universitiesGlobal: 'Global universities', relatedTechnologies: 'Related technologies',
    relatedPathways: 'Related pathways', competitions: 'Competitions & resources', technologyNotFound: 'Technology not found', technologyNotFoundText: 'This technology may have been renamed or removed.',
  },
  ar: {
    mainNavigation: 'التنقل الرئيسي', switchLanguage: 'تبديل اللغة', toggleMenu: 'فتح القائمة', orbitAria: 'استكشف تقنيات المستقبل',
    filmPlay: 'تشغيل الفيلم', filmPause: 'إيقاف الفيلم مؤقتاً', filmMute: 'كتم صوت الفيلم', filmUnmute: 'تشغيل صوت الفيلم',
    signalsEyebrow: 'إشارات المستقبل', signalsTitle: <>المستقبل بدأ بالفعل<br/><span>وهو في حركة مستمرة.</span></>,
    missionEyebrow: 'مهمتنا', missionTitle: <>تمكين الجيل القادم من المبتكرين من <span>تشكيل عالم المستقبل.</span></>,
    missionText: 'أفكارك مهمة وفضولك قوة. تصلك منصة مواهب ATRC بالمعرفة والفرص لتحويل كليهما إلى أثر حقيقي.', missionCta: 'عن مواهب ATRC',
    directionEyebrow: 'اعثر على اتجاهك', directionTitle: <>أكثر من مجرد مهنة.<br/><span>مسار نحو الأثر.</span></>, directionCta: 'عرض جميع المسارات',
    quizEyebrow: 'لست متأكداً من أين تبدأ؟', quizTitle: <>قد يكون مستقبلك<br/>على بُعد سؤال واحد.</>,
    innerIntro: 'استخدم هذه الصفحة كنقطة انطلاق لاختيار المجال المناسب، وفهم الخطوات التالية، وربط الفضول بفرص واقعية.',
    startExploring: 'ابدأ الاستكشاف', whatYouFind: 'ما الذي ستجده', chooseSignal: <>اختر إشارة.<br/><span>واتبع الزخم.</span></>, explore: 'استكشف',
    howItWorks: 'كيف يعمل', clearPath: 'مسار واضح من الاهتمام إلى الفعل.', findMatch: 'اكتشف ما يناسبك', pathQuestion: <>أي مسار يناسب<br/>طريقة تفكيرك؟</>,
    techKicker: 'استكشف ركائز عالم الغد', techTitle: <>التقنيات<br/><span>المتقدمة</span></>, techLead: 'من الأنظمة الكمية إلى الآلات الذكية، استكشف المجالات التي تعيد تعريف الممكن والأشخاص الذين سيقودونها.',
    techSearch: 'ابحث في التقنيات أو المهن', results: 'نتائج', filterAria: 'تصفية التقنيات', all: 'الكل',
    save: 'حفظ', remove: 'إزالة', exploreTechnology: 'استكشف التقنية', noSignal: 'لم نعثر على نتيجة.', noSignalText: 'جرّب تقنية أو مهنة أو فئة أخرى.', resetSearch: 'إعادة ضبط البحث',
    techSignalEyebrow: 'من الفكرة إلى المجال', techSignalTitle: <>تصبح التقنية أوضح<br/><span>عندما ترى أين تعمل.</span></>,
    techSignals: [
      ['اكتشف', 'تصفّح المجالات التي تتوافق مع فضولك.', '01'],
      ['قارن', 'افهم كيف ترتبط المهن بالقدرات المطلوبة.', '02'],
      ['قرّر', 'احفظ الإشارات التي تستحق نظرة أعمق.', '03'],
    ],
    techQuestion: <>أي تقنية مستقبلية<br/>تناسب طريقة تفكيرك؟</>,
    footerNavigation: 'التنقل في تذييل الصفحة', ecosystem: 'منظومة ATRC', location: 'أبوظبي، الإمارات العربية المتحدة', privacy: 'الخصوصية', terms: 'الشروط', accessibility: 'إمكانية الوصول',
    footerTagline: <>المواهب. التقنية.<br/>التحوّل.</>, visitAtrc: 'زيارة ATRC.gov.ae', exploreGroup: 'استكشف', supportGroup: 'الدعم', legalGroup: 'قانوني', about: 'عن المنصة', contact: 'تواصل معنا', faq: 'الأسئلة الشائعة', usefulMaterials: 'مواد مفيدة',
    backToCatalogue: 'العودة إلى التقنيات', introduction: 'مقدمة', whyItMatters: 'لماذا هي مهمة', keySubjects: 'المواد الأساسية للدراسة', technologyDomains: 'مجالات التقنية', technologyGoals: 'أهداف التقنية',
    educationRequirements: 'المتطلبات التعليمية', professions: 'المهن', responsibilities: 'المسؤوليات', requiredQualifications: 'المؤهلات المطلوبة', qualificationLevels: 'مستويات التأهيل',
    recommendedProgrammes: 'البرامج الموصى بها', studyRoutes: 'مسارات الدراسة', universitiesUae: 'الجامعات الإماراتية', universitiesGlobal: 'الجامعات العالمية', relatedTechnologies: 'تقنيات ذات صلة',
    relatedPathways: 'مسارات ذات صلة', competitions: 'مسابقات وموارد', technologyNotFound: 'التقنية غير موجودة', technologyNotFoundText: 'قد تكون هذه التقنية أعيدت تسميتها أو أزيلت.',
  },
}
