export const technologies = [
  {
    id: 'ai-digital-science',
    number: '01',
    title: 'AI & Digital Science',
    arabic: 'الذكاء الاصطناعي والعلوم الرقمية',
    arabicDescription: 'علّم الآلات على الاستدلال واكتشاف الأنماط، وابتكر أنظمة ذكية تحسّن حياتنا اليومية.',
    category: 'Digital',
    arabicCategory: 'الرقمية',
    description: 'Teach machines to reason, discover patterns and build intelligent systems that improve everyday life.',
    careers: ['AI Engineer', 'Data Scientist', 'UX Researcher'],
    arabicCareers: ['مهندس ذكاء اصطناعي', 'عالم بيانات', 'باحث تجربة المستخدم'],
    color: '#9a55ff',
    icon: 'neural',
  },
  {
    id: 'quantum',
    number: '02',
    title: 'Quantum',
    arabic: 'الكم',
    arabicDescription: 'سخّر السلوك المدهش للمادة لإحداث تحوّل في الحوسبة والاستشعار والاتصالات.',
    category: 'Science',
    arabicCategory: 'العلوم',
    description: 'Harness the strange behaviour of matter to transform computing, sensing and communication.',
    careers: ['Quantum Researcher', 'Photonics Engineer'],
    arabicCareers: ['باحث في الكم', 'مهندس فوتونيات'],
    color: '#4f83ff',
    icon: 'orbit',
  },
  {
    id: 'space-propulsion',
    number: '03',
    title: 'Propulsion & Space',
    arabic: 'الدفع والفضاء',
    arabicDescription: 'صمّم الأنظمة التي تنقل الطائرات والمركبات الفضائية إلى مدى أبعد وبكفاءة أكبر.',
    category: 'Engineering',
    arabicCategory: 'الهندسة',
    description: 'Design the systems that move aircraft and spacecraft farther, faster and more sustainably.',
    careers: ['Aerospace Engineer', 'Mission Scientist'],
    arabicCareers: ['مهندس طيران وفضاء', 'عالم مهمات فضائية'],
    color: '#f572d0',
    icon: 'rocket',
  },
  {
    id: 'autonomous-robotics',
    number: '04',
    title: 'Autonomous Robotics',
    arabic: 'الروبوتات المستقلة',
    arabicDescription: 'ابتكر آلات تدرك محيطها وتتخذ القرارات وتعمل بأمان إلى جانب الإنسان.',
    category: 'Engineering',
    arabicCategory: 'الهندسة',
    description: 'Create machines that perceive, decide and safely act alongside people in the real world.',
    careers: ['Robotics Engineer', 'Controls Specialist'],
    arabicCareers: ['مهندس روبوتات', 'اختصاصي أنظمة تحكم'],
    color: '#61d9ff',
    icon: 'robot',
  },
  {
    id: 'sustainable-energy',
    number: '05',
    title: 'Sustainable Energy',
    arabic: 'الطاقة المستدامة',
    arabicDescription: 'أعد تصوّر طرق إنتاج الطاقة وتخزينها واستخدامها لبناء مستقبل مستدام ومرن.',
    category: 'Climate',
    arabicCategory: 'المناخ',
    description: 'Reimagine how energy is generated, stored and used to power a resilient net-zero future.',
    careers: ['Energy Scientist', 'Climate Strategist'],
    arabicCareers: ['عالم طاقة', 'استراتيجي مناخ'],
    color: '#92ffb7',
    icon: 'energy',
  },
  {
    id: 'secure-systems',
    number: '06',
    title: 'Secure Systems',
    arabic: 'الأنظمة الآمنة',
    arabicDescription: 'احمِ العالم المتصل عبر الأمن السيبراني والتشفير والبنية التحتية المرنة.',
    category: 'Digital',
    arabicCategory: 'الرقمية',
    description: 'Protect the connected world through cybersecurity, cryptography and resilient infrastructure.',
    careers: ['Security Analyst', 'Cryptographer'],
    arabicCareers: ['محلل أمن سيبراني', 'اختصاصي تشفير'],
    color: '#f7c75f',
    icon: 'shield',
  },
  {
    id: 'advanced-materials',
    number: '07',
    title: 'Advanced Materials',
    arabic: 'المواد المتقدمة',
    arabicDescription: 'ابتكر مواد أخف وأقوى وأكثر ذكاءً تفتح آفاقاً وإمكانات جديدة بالكامل.',
    category: 'Science',
    arabicCategory: 'العلوم',
    description: 'Invent lighter, stronger and smarter materials that unlock entirely new possibilities.',
    careers: ['Materials Scientist', 'Nanotech Engineer'],
    arabicCareers: ['عالم مواد', 'مهندس تقنيات النانو'],
    color: '#ff785e',
    icon: 'crystal',
  },
  {
    id: 'directed-energy',
    number: '08',
    title: 'Directed Energy',
    arabic: 'الطاقة الموجهة',
    arabicDescription: 'استكشف أنظمة دقيقة توظف الطاقة الكهرومغناطيسية للاستشعار والاتصال والحماية.',
    category: 'Science',
    arabicCategory: 'العلوم',
    description: 'Explore precision systems using electromagnetic energy for sensing, communication and defence.',
    careers: ['Optical Engineer', 'Applied Physicist'],
    arabicCareers: ['مهندس بصريات', 'فيزيائي تطبيقي'],
    color: '#cf7cff',
    icon: 'beam',
  },
]

export const stats = [
  { value: '85M', label: 'technology roles may be created globally by 2030', arabicLabel: 'وظيفة تقنية قد يتم استحداثها عالمياً بحلول عام 2030', source: 'Future of Jobs', arabicSource: 'مستقبل الوظائف', icon: 'data' },
  { value: '50K', label: 'new jobs projected through Abu Dhabi smart mobility', arabicLabel: 'وظيفة جديدة متوقعة بفضل التنقل الذكي في أبوظبي', source: 'Future in motion', arabicSource: 'المستقبل في حركة', icon: 'speed' },
  { value: '2050', label: 'the UAE Net Zero horizon shaping clean innovation', arabicLabel: 'أفق الحياد المناخي لدولة الإمارات الذي يرسم ملامح الابتكار النظيف', source: 'Net Zero UAE', arabicSource: 'الحياد المناخي في الإمارات', icon: 'bolt' },
]

export const announcements = [
  {
    icon: 'neural', color: '#9a55ff',
    text: 'The future starts here. Our STEM programme empowers students to explore cutting-edge technologies, discover their strengths, and turn ideas into action. Join a new generation of innovators.',
    arabicText: 'المستقبل يبدأ من هنا. يمكّن برنامج STEM الطلاب من استكشاف أحدث التقنيات، واكتشاف نقاط قوتهم، وتحويل الأفكار إلى أفعال. انضم إلى جيل جديد من المبتكرين.',
  },
  {
    icon: 'rocket', color: '#f572d0',
    text: 'Registrations are now open for the ATRC summer accelerator — a hands-on sprint into robotics, quantum and space systems for ambitious students.',
    arabicText: 'التسجيل مفتوح الآن في برنامج التسريع الصيفي لمجلس أبحاث التكنولوجيا المتطورة، وهو تجربة عملية في الروبوتات والحوسبة الكمية وأنظمة الفضاء للطلاب الطموحين.',
  },
]

export const pathways = [
  { title: 'Future Builder', arabicTitle: 'باني المستقبل', role: 'Engineers', arabicRole: 'المهندسون', mark: 'B', color: '#8c48ff' },
  { title: 'Future Explorer', arabicTitle: 'مستكشف المستقبل', role: 'Scientists', arabicRole: 'العلماء', mark: 'E', color: '#316dff' },
  { title: 'Future Analyst', arabicTitle: 'محلل المستقبل', role: 'Data & Finance', arabicRole: 'البيانات والتمويل', mark: 'A', color: '#e95ecb' },
  { title: 'Future Creator', arabicTitle: 'مبدع المستقبل', role: 'Design & Immersive', arabicRole: 'التصميم والتجارب الغامرة', mark: 'C', color: '#31c7e8' },
]
