export const technologies = [
  {
    id: 'ai-digital-science',
    number: '01',
    title: 'AI & Digital Science',
    arabic: 'الذكاء الاصطناعي والعلوم الرقمية',
    arabicDescription: 'علّم الآلات على الاستدلال واكتشاف الأنماط، وابتكر أنظمة ذكية تحسّن حياتنا اليومية.',
    category: 'Digital',
    description: 'Teach machines to reason, discover patterns and build intelligent systems that improve everyday life.',
    careers: ['AI Engineer', 'Data Scientist', 'UX Researcher'],
    color: '#9a55ff',
    icon: 'neural',
  },
  {
    id: 'quantum',
    number: '02',
    title: 'Quantum',
    arabic: 'الكم',
    arabicDescription: 'سخّر السلوك المدهش للمادة لإحداث تحوّل في الحوسبة والاستشعار والاتصالات.',
    category: 'Science',
    description: 'Harness the strange behaviour of matter to transform computing, sensing and communication.',
    careers: ['Quantum Researcher', 'Photonics Engineer'],
    color: '#4f83ff',
    icon: 'orbit',
  },
  {
    id: 'space-propulsion',
    number: '03',
    title: 'Propulsion & Space',
    arabic: 'الدفع والفضاء',
    arabicDescription: 'صمّم الأنظمة التي تنقل الطائرات والمركبات الفضائية إلى مدى أبعد وبكفاءة أكبر.',
    category: 'Engineering',
    description: 'Design the systems that move aircraft and spacecraft farther, faster and more sustainably.',
    careers: ['Aerospace Engineer', 'Mission Scientist'],
    color: '#f572d0',
    icon: 'rocket',
  },
  {
    id: 'autonomous-robotics',
    number: '04',
    title: 'Autonomous Robotics',
    arabic: 'الروبوتات المستقلة',
    arabicDescription: 'ابتكر آلات تدرك محيطها وتتخذ القرارات وتعمل بأمان إلى جانب الإنسان.',
    category: 'Engineering',
    description: 'Create machines that perceive, decide and safely act alongside people in the real world.',
    careers: ['Robotics Engineer', 'Controls Specialist'],
    color: '#61d9ff',
    icon: 'robot',
  },
  {
    id: 'sustainable-energy',
    number: '05',
    title: 'Sustainable Energy',
    arabic: 'الطاقة المستدامة',
    arabicDescription: 'أعد تصوّر طرق إنتاج الطاقة وتخزينها واستخدامها لبناء مستقبل مستدام ومرن.',
    category: 'Climate',
    description: 'Reimagine how energy is generated, stored and used to power a resilient net-zero future.',
    careers: ['Energy Scientist', 'Climate Strategist'],
    color: '#92ffb7',
    icon: 'energy',
  },
  {
    id: 'secure-systems',
    number: '06',
    title: 'Secure Systems',
    arabic: 'الأنظمة الآمنة',
    arabicDescription: 'احمِ العالم المتصل عبر الأمن السيبراني والتشفير والبنية التحتية المرنة.',
    category: 'Digital',
    description: 'Protect the connected world through cybersecurity, cryptography and resilient infrastructure.',
    careers: ['Security Analyst', 'Cryptographer'],
    color: '#f7c75f',
    icon: 'shield',
  },
  {
    id: 'advanced-materials',
    number: '07',
    title: 'Advanced Materials',
    arabic: 'المواد المتقدمة',
    arabicDescription: 'ابتكر مواد أخف وأقوى وأكثر ذكاءً تفتح آفاقاً وإمكانات جديدة بالكامل.',
    category: 'Science',
    description: 'Invent lighter, stronger and smarter materials that unlock entirely new possibilities.',
    careers: ['Materials Scientist', 'Nanotech Engineer'],
    color: '#ff785e',
    icon: 'crystal',
  },
  {
    id: 'directed-energy',
    number: '08',
    title: 'Directed Energy',
    arabic: 'الطاقة الموجهة',
    arabicDescription: 'استكشف أنظمة دقيقة توظف الطاقة الكهرومغناطيسية للاستشعار والاتصال والحماية.',
    category: 'Science',
    description: 'Explore precision systems using electromagnetic energy for sensing, communication and defence.',
    careers: ['Optical Engineer', 'Applied Physicist'],
    color: '#cf7cff',
    icon: 'beam',
  },
]

export const stats = [
  { value: '85M', label: 'technology roles may be created globally by 2030', source: 'Future of Jobs' },
  { value: '50K', label: 'new jobs projected through Abu Dhabi smart mobility', source: 'Future in motion' },
  { value: '2050', label: 'the UAE Net Zero horizon shaping clean innovation', source: 'Net Zero UAE' },
]

export const pathways = [
  { title: 'Future Builder', role: 'Engineers', mark: 'B', color: '#8c48ff' },
  { title: 'Future Explorer', role: 'Scientists', mark: 'E', color: '#316dff' },
  { title: 'Future Analyst', role: 'Data & Finance', mark: 'A', color: '#e95ecb' },
  { title: 'Future Creator', role: 'Design & Immersive', mark: 'C', color: '#31c7e8' },
]
